# Generated by Django 4.2.5 on 2023-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='tittle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
