# Generated by Django 4.2.5 on 2023-09-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_logo_name_alter_logo_image_alter_logo_tittle'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='minilogo',
            field=models.ImageField(null=True, upload_to='minilogo'),
        ),
    ]
