# Generated by Django 4.2.5 on 2023-09-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_logo_image_alter_logo_minilogo_alter_logo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='default',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
