# Generated by Django 4.2.5 on 2023-09-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='description',
        ),
    ]
