# Generated by Django 4.2.5 on 2023-09-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_header2'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='header',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='header2',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='header2',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
