# Generated by Django 4.2.5 on 2023-09-14 10:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_header_available_header_date_header2_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
    ]
