# Generated by Django 4.2.5 on 2023-09-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_header_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
