# Generated by Django 4.2.5 on 2023-09-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_header_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='slug',
        ),
    ]
