# Generated by Django 4.2.5 on 2023-09-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_header2_description_header2_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header2',
            name='description',
        ),
        migrations.RemoveField(
            model_name='header2',
            name='view',
        ),
    ]
