# Generated by Django 4.2.5 on 2023-09-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_header2_description_header2_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='adversiment',
            field=models.ImageField(blank=True, null=True, upload_to='ads'),
        ),
        migrations.AddField(
            model_name='header',
            name='adversiment2',
            field=models.ImageField(blank=True, null=True, upload_to='ads'),
        ),
        migrations.AddField(
            model_name='header2',
            name='adversiment',
            field=models.ImageField(blank=True, null=True, upload_to='ads'),
        ),
        migrations.AddField(
            model_name='header2',
            name='adversiment2',
            field=models.ImageField(blank=True, null=True, upload_to='ads'),
        ),
    ]
