# Generated by Django 4.2.5 on 2023-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_header_adversiment_header_adversiment2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAdversiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.ImageField(blank=True, null=True, upload_to='ads')),
                ('ads2', models.ImageField(blank=True, null=True, upload_to='ads')),
                ('ads3', models.ImageField(blank=True, null=True, upload_to='ads')),
                ('ads4', models.ImageField(blank=True, null=True, upload_to='ads')),
                ('date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
