# Generated by Django 4.2.5 on 2023-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_mainadversiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainadversiment',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header2',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
