# Generated by Django 4.2.5 on 2023-09-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_header_name_alter_header2_name_alter_logo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
