# Generated by Django 4.2.5 on 2023-09-15 11:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_logo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('adversiment', models.ImageField(blank=True, null=True, upload_to='ads')),
                ('view', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
