# Generated by Django 4.2.5 on 2023-09-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_rename_adversiment_blog_adversiment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='adversiment4',
            field=models.ImageField(blank=True, null=True, upload_to='ads'),
        ),
    ]
