# Generated by Django 4.2.5 on 2023-09-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_adversiment_header_adversiment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainadversiment',
            name='adsnavbar',
            field=models.ImageField(blank=True, null=True, upload_to='ads'),
        ),
    ]
