# Generated by Django 4.2.5 on 2023-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_mainadversiment_adsnavbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainadversiment',
            name='adsheader',
            field=models.ImageField(blank=True, null=True, upload_to='ads'),
        ),
    ]
