# Generated by Django 4.2.5 on 2023-09-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_mainadversiment_adsheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainadversiment',
            name='urlnavbar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
