# Generated by Django 4.2.5 on 2023-09-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_mainadversiment_urlads_mainadversiment_urlads2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainadversiment',
            old_name='urlheaderurl',
            new_name='urlheader',
        ),
    ]
