# Generated by Django 4.2.5 on 2023-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_allsingleadversiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='urladverhome',
            field=models.URLField(blank=True, null=True),
        ),
    ]
