# Generated by Django 4.2.5 on 2023-09-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='room',
            new_name='suggest',
        ),
    ]
