# Generated by Django 4.2.5 on 2023-09-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_room_suggestion_suggest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('facebook', models.URLField(blank=True, max_length=100)),
                ('twittter', models.URLField(blank=True, max_length=100)),
                ('instagram', models.URLField(blank=True, max_length=100)),
                ('google', models.URLField(blank=True, max_length=100)),
                ('pinterest', models.URLField(blank=True, max_length=100)),
            ],
        ),
    ]
