# Generated by Django 4.2.5 on 2023-09-18 12:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='google',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='pinterest',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twittter',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
