# Generated by Django 4.2.5 on 2023-09-18 18:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_footer_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='copyright_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='year',
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
