# Generated by Django 4.2.5 on 2023-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='tittle_main',
            field=models.TextField(blank=True, null=True),
        ),
    ]
