# Generated by Django 4.2.5 on 2023-09-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_name_tittle_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='alsolike',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='follow',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='home',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='news',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='popular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='privacy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
