# Generated by Django 4.2.5 on 2023-09-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
