# Generated by Django 4.2.5 on 2023-09-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
